name: Deploy to Amazon Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2